name: Generate Commit Stats

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate Stats File
      run: |
        mkdir -p stats
        echo "Repository Statistics" > stats/commit-stats.txt
        echo "Generated on: $(date)" >> stats/commit-stats.txt
        echo "\nCommit History:" >> stats/commit-stats.txt
        git log --stat >> stats/commit-stats.txt
        echo "\nTotal Commits: $(git rev-list --count HEAD)" >> stats/commit-stats.txt
        echo "\nContributors: $(git shortlog -s -n --all | wc -l)" >> stats/commit-stats.txt

    - name: Commit Stats
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add stats/commit-stats.txt
        git commit -m "Update commit statistics [skip ci]"
        git push
