name: Tokei Stats (On Demand)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tokei-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Install Tokei
        run: |
          sudo apt-get update
          sudo apt-get install -y cargo
          cargo install tokei

      - name: Run Tokei
        run: |
          tokei --output json . > tokei-stats.json
          echo "Tokei stats generated!"

      - name: Commit Stats
        uses: EndBug/add-and-commit@v9
        with:
            author_name: Alejandro Garcia
            author_email: agarciafdz@gmail.com
            message: 'Update code stats'
            add: 'tokei-stats.json'
            github_token: ${{ secrets.GITHUB_TOKEN }}
