name: Tokei Stats (On Demand)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tokei-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Install Tokei
        run: |
          sudo apt-get update
          sudo apt-get install -y cargo
          cargo install tokei

      - name: Install jfq for jsonata
        run: |
          npm install --global jfq

      - name: Install gron
        run: |
          # Download latest gron Linux build (zipped)
          wget https://github.com/tomnomnom/gron/releases/download/v0.7.1/gron-freebsd-amd64-0.7.1.tgz
          tar -xzvf gron-freebsd-amd64-0.7.1.tgz
          chmod +x gron
          sudo mv gron /usr/local/bin/gron

      - name: Verify gron is installed
        run: gron --version

      - name: Run Tokei
        run: |
          tokei --output json | jfq --query-file docs/stats/add_total_to_markdown.jsonata | ./gron > docs/stats/tokei-stats.gron
          echo "Tokei stats generated!"

      - name: Commit Stats
        uses: EndBug/add-and-commit@v9
        with:
            author_name: Alejandro Garcia
            author_email: agarciafdz@gmail.com
            message: 'Update code stats'
            add: 'docs/stats/tokei-stats.gron'
            github_token: ${{ secrets.GITHUB_TOKEN }}
